FROM quay.io/minio/minio:latest

RUN mkdir -p /data/devbucket
RUN mkdir -p /data/.minio.sys/buckets/devbucket
COPY ./policy.json /data/.minio.sys/buckets/devbucket/policy.json

ENTRYPOINT ["minio", "server", "/data", "--console-address", ":9001"]