version: "3.8"

# ネットワークを作成
networks:
  app-network:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      # - ../..:/workspaces:cached
      # ワークスペースにリポジトリのデータをマウント
      - type: bind
        source: ../
        target: /workspaces/repo
        consistency: cached
      # ルートのnode_modulesをボリュームにマウント
      - type: volume
        source: root-data
        target: /workspaces/repo/node_modules
      # フロントのnode_modulesをボリュームにマウント
      - type: volume
        source: frontend-data
        target: /workspaces/repo/packages/frontend/node_modules
      # バックのnode_modulesをボリュームにマウント
      - type: volume
        source: backend-data
        target: /workspaces/repo/packages/backend/node_modules

    environment:
      - SCHEMA_PATH=../graphql/schemas/*.graphql
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
      # - OPERATION_PATH=../graphql/operations/*.graphql
    # アプリケーションコンテナの環境変数を読み込む
    env_file: ${BACK_ENV}

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    networks:
      - app-network
    # depends_on:
    #   db:
    #     condition: service_healthy

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data
    # ポスグレの環境変数を読み込む
    env_file: ${POSTGRES_ENV}
    networks:
      - app-network

  minio:
    build:
      context: .
      dockerfile: Dockerfile.minio
    restart: unless-stopped
    volumes:
      - type: volume
        source: minio-data
        target: /data
    # minioの環境変数を読み込む
    env_file: ${MINIO_ENV}
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    networks:
      - app-network
    ports:
      - 9000:9000
      - 9001:9001
volumes:
  postgres-data:
  minio-data:
  root-data:
  frontend-data:
  backend-data:
